project:
  type: website
  output-dir: docs

website:
  open-graph: true
  site-url: https://shamiecc.github.io/ 
  favicon: images/world_icon.png
  google-analytics: 
    tracking-id: "G-3YCVJ3TKDX" #"UA-242992767-1"
    anonymize-ip: true
  title: ""
  sidebar: true
  search: false
  navbar:
    logo: images/logo_nav.png
    left:
      - text: Home Page
        href: index.qmd
      - text: About Caroline Shamiso
        href: about.qmd

    right:
      - href: posts.qmd
      - href: resources.qmd
      - text: "Let's Get in Touch!"
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/caroline-shamiso-chitongo-7724381a8/
          - icon: github
            text: GitHub
            href: https://github.com/ShamieCC
          - icon: envelope
            text: Email
            href: mailto:chitongo.shamiso@gmail.com

  page-footer:
    background: light
    left: "© 2024 Caroline Shamiso Chitongo"
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/ShamieCC){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
      #- icon: github
      # href: https://github.com/ShamieCC
      #- icon: linkedin
      #  href: https://www.linkedin.com/in/caroline-shamiso-chitongo-7724381a8/

format:
  html:
    theme:
      - mystyles.scss
    page-layout: full
    mainfont: Nunito
    css: styles.css
    toc: true
    editor: visual
