project:
  type: website
  output-dir: docs

website:
  favicon: images/world_icon.png
  title: ""
  sidebar: true
  search: false
  navbar:
    logo: images/logo_nav.png
    left:
      - text: Home Page
        href: index.qmd
      - text: About Caroline Shamiso
        href: about.qmd

    right:
      - text: My Portifolio
        href: posts.qmd
      - text: "Let's Get in Touch!"
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/caroline-shamiso-chitongo-7724381a8/
          - icon: github
            text: GitHub
            href: https://github.com/ShamieCC
          - icon: envelope
            text: Email
            href: mailto:chitongo.shamiso@gmail.com

  page-footer:
    background: "#4E7895"
    left: "© 2024 Caroline Shamiso Chitongo"
    right:
      - icon: github
        href: https://github.com/ShamieCC
      - icon: linkedin
        href: https://www.linkedin.com/in/caroline-shamiso-chitongo-7724381a8/

format:
  html:
    theme:
      - mystyles.scss
    page-layout: full
    mainfont: Avenir
    backgroundcolor: "#FAFAF9"
    css: styles.css
    toc: true
    editor: visual
